---
title: "Chicago"
author: "Mauricio Moreno"
date: "2022-12-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#load in libraries
```{r, warning=FALSE}
library(leaflet)
library(tidyverse)
```


#importing the chicago data
```{r}
data_raw <- read.csv("Data/grocery-stores-2013.csv")

#keeping only longitude and latitude info
store_locations <- data_raw[,c(1,15:16)]

#create dummy if stores are one type vs another
store_types <- store_locations %>%
  mutate(small = case_when(
    str_detect(store_locations$STORE.NAME, "MART") ~ 1,
    str_detect(store_locations$STORE.NAME, "LIQUOR") ~ 1,
    str_detect(store_locations$STORE.NAME, "LIQUORS") ~ 1,
    str_detect(store_locations$STORE.NAME, "CARNICERIA") ~ 1,
    str_detect(store_locations$STORE.NAME, "DOLLAR") ~ 1,
    str_detect(store_locations$STORE.NAME, "WALGREENS") ~ 1,
    TRUE ~ 0))
```

#mapping out the locations
```{r}
#mybins <- c(0,1)
my_pal <- colorBin(palette= c("black", "red"), domain=store_types$small, na.color="transparent")

map <- store_types %>%
  leaflet() %>%
  addTiles() %>%
  addCircleMarkers(radius = 3,
                   lng = store_types$LONGITUDE,
                   lat = store_types$LATITUDE,
                   color = ~my_pal(small),
                   popup = store_types$STORE.NAME)

map
```


mybins <- c(1,500,1000,1500,2000,2500,3000)
my_pal <- colorBin( palette="OrRd", domain=listingsleaflet$price, na.color="transparent", bins=mybins)

